### ISSUE TITLE
大佬能否写一个支持yunzai的这个插件

### ISSUE THREAD

**Issue by Xingheee** [NanakaNeko/zhenxun_a2s_query#1]
愿意赞助，邮箱xinghe2020@outlook.com

**Comment by NanakaNeko** [comment]
我没用过yunzai，不知道是什么格式的

**Comment by NanakaNeko** [comment]
看了一眼，云崽插件是js的，从头写很麻烦，不如参照云崽的md介绍，再装一个真寻，实现一个QQ两个机器人
